# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  client:
    cmds:
      - dart run pigeon
        --input pigeons/rustore.dart