// Autogenerated from Pigeon (v17.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package ru.rustore.flutter_rustore_billing.pigeons;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Rustore {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SubscriptionPeriod {
    private @NonNull Long years;

    public @NonNull Long getYears() {
      return years;
    }

    public void setYears(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"years\" is null.");
      }
      this.years = setterArg;
    }

    private @NonNull Long months;

    public @NonNull Long getMonths() {
      return months;
    }

    public void setMonths(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"months\" is null.");
      }
      this.months = setterArg;
    }

    private @NonNull Long days;

    public @NonNull Long getDays() {
      return days;
    }

    public void setDays(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"days\" is null.");
      }
      this.days = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SubscriptionPeriod() {}

    public static final class Builder {

      private @Nullable Long years;

      @CanIgnoreReturnValue
      public @NonNull Builder setYears(@NonNull Long setterArg) {
        this.years = setterArg;
        return this;
      }

      private @Nullable Long months;

      @CanIgnoreReturnValue
      public @NonNull Builder setMonths(@NonNull Long setterArg) {
        this.months = setterArg;
        return this;
      }

      private @Nullable Long days;

      @CanIgnoreReturnValue
      public @NonNull Builder setDays(@NonNull Long setterArg) {
        this.days = setterArg;
        return this;
      }

      public @NonNull SubscriptionPeriod build() {
        SubscriptionPeriod pigeonReturn = new SubscriptionPeriod();
        pigeonReturn.setYears(years);
        pigeonReturn.setMonths(months);
        pigeonReturn.setDays(days);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(years);
      toListResult.add(months);
      toListResult.add(days);
      return toListResult;
    }

    static @NonNull SubscriptionPeriod fromList(@NonNull ArrayList<Object> list) {
      SubscriptionPeriod pigeonResult = new SubscriptionPeriod();
      Object years = list.get(0);
      pigeonResult.setYears((years == null) ? null : ((years instanceof Integer) ? (Integer) years : (Long) years));
      Object months = list.get(1);
      pigeonResult.setMonths((months == null) ? null : ((months instanceof Integer) ? (Integer) months : (Long) months));
      Object days = list.get(2);
      pigeonResult.setDays((days == null) ? null : ((days instanceof Integer) ? (Integer) days : (Long) days));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Subscription {
    private @Nullable SubscriptionPeriod subscriptionPeriod;

    public @Nullable SubscriptionPeriod getSubscriptionPeriod() {
      return subscriptionPeriod;
    }

    public void setSubscriptionPeriod(@Nullable SubscriptionPeriod setterArg) {
      this.subscriptionPeriod = setterArg;
    }

    private @Nullable SubscriptionPeriod freeTrialPeriod;

    public @Nullable SubscriptionPeriod getFreeTrialPeriod() {
      return freeTrialPeriod;
    }

    public void setFreeTrialPeriod(@Nullable SubscriptionPeriod setterArg) {
      this.freeTrialPeriod = setterArg;
    }

    private @Nullable SubscriptionPeriod gracePeriod;

    public @Nullable SubscriptionPeriod getGracePeriod() {
      return gracePeriod;
    }

    public void setGracePeriod(@Nullable SubscriptionPeriod setterArg) {
      this.gracePeriod = setterArg;
    }

    private @Nullable String introductoryPrice;

    public @Nullable String getIntroductoryPrice() {
      return introductoryPrice;
    }

    public void setIntroductoryPrice(@Nullable String setterArg) {
      this.introductoryPrice = setterArg;
    }

    private @Nullable String introductoryPriceAmount;

    public @Nullable String getIntroductoryPriceAmount() {
      return introductoryPriceAmount;
    }

    public void setIntroductoryPriceAmount(@Nullable String setterArg) {
      this.introductoryPriceAmount = setterArg;
    }

    private @Nullable SubscriptionPeriod introductoryPricePeriod;

    public @Nullable SubscriptionPeriod getIntroductoryPricePeriod() {
      return introductoryPricePeriod;
    }

    public void setIntroductoryPricePeriod(@Nullable SubscriptionPeriod setterArg) {
      this.introductoryPricePeriod = setterArg;
    }

    public static final class Builder {

      private @Nullable SubscriptionPeriod subscriptionPeriod;

      @CanIgnoreReturnValue
      public @NonNull Builder setSubscriptionPeriod(@Nullable SubscriptionPeriod setterArg) {
        this.subscriptionPeriod = setterArg;
        return this;
      }

      private @Nullable SubscriptionPeriod freeTrialPeriod;

      @CanIgnoreReturnValue
      public @NonNull Builder setFreeTrialPeriod(@Nullable SubscriptionPeriod setterArg) {
        this.freeTrialPeriod = setterArg;
        return this;
      }

      private @Nullable SubscriptionPeriod gracePeriod;

      @CanIgnoreReturnValue
      public @NonNull Builder setGracePeriod(@Nullable SubscriptionPeriod setterArg) {
        this.gracePeriod = setterArg;
        return this;
      }

      private @Nullable String introductoryPrice;

      @CanIgnoreReturnValue
      public @NonNull Builder setIntroductoryPrice(@Nullable String setterArg) {
        this.introductoryPrice = setterArg;
        return this;
      }

      private @Nullable String introductoryPriceAmount;

      @CanIgnoreReturnValue
      public @NonNull Builder setIntroductoryPriceAmount(@Nullable String setterArg) {
        this.introductoryPriceAmount = setterArg;
        return this;
      }

      private @Nullable SubscriptionPeriod introductoryPricePeriod;

      @CanIgnoreReturnValue
      public @NonNull Builder setIntroductoryPricePeriod(@Nullable SubscriptionPeriod setterArg) {
        this.introductoryPricePeriod = setterArg;
        return this;
      }

      public @NonNull Subscription build() {
        Subscription pigeonReturn = new Subscription();
        pigeonReturn.setSubscriptionPeriod(subscriptionPeriod);
        pigeonReturn.setFreeTrialPeriod(freeTrialPeriod);
        pigeonReturn.setGracePeriod(gracePeriod);
        pigeonReturn.setIntroductoryPrice(introductoryPrice);
        pigeonReturn.setIntroductoryPriceAmount(introductoryPriceAmount);
        pigeonReturn.setIntroductoryPricePeriod(introductoryPricePeriod);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add((subscriptionPeriod == null) ? null : subscriptionPeriod.toList());
      toListResult.add((freeTrialPeriod == null) ? null : freeTrialPeriod.toList());
      toListResult.add((gracePeriod == null) ? null : gracePeriod.toList());
      toListResult.add(introductoryPrice);
      toListResult.add(introductoryPriceAmount);
      toListResult.add((introductoryPricePeriod == null) ? null : introductoryPricePeriod.toList());
      return toListResult;
    }

    static @NonNull Subscription fromList(@NonNull ArrayList<Object> list) {
      Subscription pigeonResult = new Subscription();
      Object subscriptionPeriod = list.get(0);
      pigeonResult.setSubscriptionPeriod((subscriptionPeriod == null) ? null : SubscriptionPeriod.fromList((ArrayList<Object>) subscriptionPeriod));
      Object freeTrialPeriod = list.get(1);
      pigeonResult.setFreeTrialPeriod((freeTrialPeriod == null) ? null : SubscriptionPeriod.fromList((ArrayList<Object>) freeTrialPeriod));
      Object gracePeriod = list.get(2);
      pigeonResult.setGracePeriod((gracePeriod == null) ? null : SubscriptionPeriod.fromList((ArrayList<Object>) gracePeriod));
      Object introductoryPrice = list.get(3);
      pigeonResult.setIntroductoryPrice((String) introductoryPrice);
      Object introductoryPriceAmount = list.get(4);
      pigeonResult.setIntroductoryPriceAmount((String) introductoryPriceAmount);
      Object introductoryPricePeriod = list.get(5);
      pigeonResult.setIntroductoryPricePeriod((introductoryPricePeriod == null) ? null : SubscriptionPeriod.fromList((ArrayList<Object>) introductoryPricePeriod));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Product {
    private @NonNull String productId;

    public @NonNull String getProductId() {
      return productId;
    }

    public void setProductId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"productId\" is null.");
      }
      this.productId = setterArg;
    }

    private @Nullable String productType;

    public @Nullable String getProductType() {
      return productType;
    }

    public void setProductType(@Nullable String setterArg) {
      this.productType = setterArg;
    }

    private @NonNull String productStatus;

    public @NonNull String getProductStatus() {
      return productStatus;
    }

    public void setProductStatus(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"productStatus\" is null.");
      }
      this.productStatus = setterArg;
    }

    private @Nullable String priceLabel;

    public @Nullable String getPriceLabel() {
      return priceLabel;
    }

    public void setPriceLabel(@Nullable String setterArg) {
      this.priceLabel = setterArg;
    }

    private @Nullable Long price;

    public @Nullable Long getPrice() {
      return price;
    }

    public void setPrice(@Nullable Long setterArg) {
      this.price = setterArg;
    }

    private @Nullable String currency;

    public @Nullable String getCurrency() {
      return currency;
    }

    public void setCurrency(@Nullable String setterArg) {
      this.currency = setterArg;
    }

    private @Nullable String language;

    public @Nullable String getLanguage() {
      return language;
    }

    public void setLanguage(@Nullable String setterArg) {
      this.language = setterArg;
    }

    private @Nullable String title;

    public @Nullable String getTitle() {
      return title;
    }

    public void setTitle(@Nullable String setterArg) {
      this.title = setterArg;
    }

    private @Nullable String description;

    public @Nullable String getDescription() {
      return description;
    }

    public void setDescription(@Nullable String setterArg) {
      this.description = setterArg;
    }

    private @Nullable String imageUrl;

    public @Nullable String getImageUrl() {
      return imageUrl;
    }

    public void setImageUrl(@Nullable String setterArg) {
      this.imageUrl = setterArg;
    }

    private @Nullable String promoImageUrl;

    public @Nullable String getPromoImageUrl() {
      return promoImageUrl;
    }

    public void setPromoImageUrl(@Nullable String setterArg) {
      this.promoImageUrl = setterArg;
    }

    private @Nullable Subscription subscription;

    public @Nullable Subscription getSubscription() {
      return subscription;
    }

    public void setSubscription(@Nullable Subscription setterArg) {
      this.subscription = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    Product() {}

    public static final class Builder {

      private @Nullable String productId;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductId(@NonNull String setterArg) {
        this.productId = setterArg;
        return this;
      }

      private @Nullable String productType;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductType(@Nullable String setterArg) {
        this.productType = setterArg;
        return this;
      }

      private @Nullable String productStatus;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductStatus(@NonNull String setterArg) {
        this.productStatus = setterArg;
        return this;
      }

      private @Nullable String priceLabel;

      @CanIgnoreReturnValue
      public @NonNull Builder setPriceLabel(@Nullable String setterArg) {
        this.priceLabel = setterArg;
        return this;
      }

      private @Nullable Long price;

      @CanIgnoreReturnValue
      public @NonNull Builder setPrice(@Nullable Long setterArg) {
        this.price = setterArg;
        return this;
      }

      private @Nullable String currency;

      @CanIgnoreReturnValue
      public @NonNull Builder setCurrency(@Nullable String setterArg) {
        this.currency = setterArg;
        return this;
      }

      private @Nullable String language;

      @CanIgnoreReturnValue
      public @NonNull Builder setLanguage(@Nullable String setterArg) {
        this.language = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@Nullable String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable String description;

      @CanIgnoreReturnValue
      public @NonNull Builder setDescription(@Nullable String setterArg) {
        this.description = setterArg;
        return this;
      }

      private @Nullable String imageUrl;

      @CanIgnoreReturnValue
      public @NonNull Builder setImageUrl(@Nullable String setterArg) {
        this.imageUrl = setterArg;
        return this;
      }

      private @Nullable String promoImageUrl;

      @CanIgnoreReturnValue
      public @NonNull Builder setPromoImageUrl(@Nullable String setterArg) {
        this.promoImageUrl = setterArg;
        return this;
      }

      private @Nullable Subscription subscription;

      @CanIgnoreReturnValue
      public @NonNull Builder setSubscription(@Nullable Subscription setterArg) {
        this.subscription = setterArg;
        return this;
      }

      public @NonNull Product build() {
        Product pigeonReturn = new Product();
        pigeonReturn.setProductId(productId);
        pigeonReturn.setProductType(productType);
        pigeonReturn.setProductStatus(productStatus);
        pigeonReturn.setPriceLabel(priceLabel);
        pigeonReturn.setPrice(price);
        pigeonReturn.setCurrency(currency);
        pigeonReturn.setLanguage(language);
        pigeonReturn.setTitle(title);
        pigeonReturn.setDescription(description);
        pigeonReturn.setImageUrl(imageUrl);
        pigeonReturn.setPromoImageUrl(promoImageUrl);
        pigeonReturn.setSubscription(subscription);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(12);
      toListResult.add(productId);
      toListResult.add(productType);
      toListResult.add(productStatus);
      toListResult.add(priceLabel);
      toListResult.add(price);
      toListResult.add(currency);
      toListResult.add(language);
      toListResult.add(title);
      toListResult.add(description);
      toListResult.add(imageUrl);
      toListResult.add(promoImageUrl);
      toListResult.add((subscription == null) ? null : subscription.toList());
      return toListResult;
    }

    static @NonNull Product fromList(@NonNull ArrayList<Object> list) {
      Product pigeonResult = new Product();
      Object productId = list.get(0);
      pigeonResult.setProductId((String) productId);
      Object productType = list.get(1);
      pigeonResult.setProductType((String) productType);
      Object productStatus = list.get(2);
      pigeonResult.setProductStatus((String) productStatus);
      Object priceLabel = list.get(3);
      pigeonResult.setPriceLabel((String) priceLabel);
      Object price = list.get(4);
      pigeonResult.setPrice((price == null) ? null : ((price instanceof Integer) ? (Integer) price : (Long) price));
      Object currency = list.get(5);
      pigeonResult.setCurrency((String) currency);
      Object language = list.get(6);
      pigeonResult.setLanguage((String) language);
      Object title = list.get(7);
      pigeonResult.setTitle((String) title);
      Object description = list.get(8);
      pigeonResult.setDescription((String) description);
      Object imageUrl = list.get(9);
      pigeonResult.setImageUrl((String) imageUrl);
      Object promoImageUrl = list.get(10);
      pigeonResult.setPromoImageUrl((String) promoImageUrl);
      Object subscription = list.get(11);
      pigeonResult.setSubscription((subscription == null) ? null : Subscription.fromList((ArrayList<Object>) subscription));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ProductsResponse {
    private @Nullable Long code;

    public @Nullable Long getCode() {
      return code;
    }

    public void setCode(@Nullable Long setterArg) {
      this.code = setterArg;
    }

    private @Nullable String errorMessage;

    public @Nullable String getErrorMessage() {
      return errorMessage;
    }

    public void setErrorMessage(@Nullable String setterArg) {
      this.errorMessage = setterArg;
    }

    private @Nullable String errorDescription;

    public @Nullable String getErrorDescription() {
      return errorDescription;
    }

    public void setErrorDescription(@Nullable String setterArg) {
      this.errorDescription = setterArg;
    }

    private @Nullable String traceId;

    public @Nullable String getTraceId() {
      return traceId;
    }

    public void setTraceId(@Nullable String setterArg) {
      this.traceId = setterArg;
    }

    private @NonNull List<Product> products;

    public @NonNull List<Product> getProducts() {
      return products;
    }

    public void setProducts(@NonNull List<Product> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"products\" is null.");
      }
      this.products = setterArg;
    }

    private @NonNull List<DigitalShopGeneralError> errors;

    public @NonNull List<DigitalShopGeneralError> getErrors() {
      return errors;
    }

    public void setErrors(@NonNull List<DigitalShopGeneralError> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"errors\" is null.");
      }
      this.errors = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ProductsResponse() {}

    public static final class Builder {

      private @Nullable Long code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@Nullable Long setterArg) {
        this.code = setterArg;
        return this;
      }

      private @Nullable String errorMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorMessage(@Nullable String setterArg) {
        this.errorMessage = setterArg;
        return this;
      }

      private @Nullable String errorDescription;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorDescription(@Nullable String setterArg) {
        this.errorDescription = setterArg;
        return this;
      }

      private @Nullable String traceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setTraceId(@Nullable String setterArg) {
        this.traceId = setterArg;
        return this;
      }

      private @Nullable List<Product> products;

      @CanIgnoreReturnValue
      public @NonNull Builder setProducts(@NonNull List<Product> setterArg) {
        this.products = setterArg;
        return this;
      }

      private @Nullable List<DigitalShopGeneralError> errors;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrors(@NonNull List<DigitalShopGeneralError> setterArg) {
        this.errors = setterArg;
        return this;
      }

      public @NonNull ProductsResponse build() {
        ProductsResponse pigeonReturn = new ProductsResponse();
        pigeonReturn.setCode(code);
        pigeonReturn.setErrorMessage(errorMessage);
        pigeonReturn.setErrorDescription(errorDescription);
        pigeonReturn.setTraceId(traceId);
        pigeonReturn.setProducts(products);
        pigeonReturn.setErrors(errors);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add(code);
      toListResult.add(errorMessage);
      toListResult.add(errorDescription);
      toListResult.add(traceId);
      toListResult.add(products);
      toListResult.add(errors);
      return toListResult;
    }

    static @NonNull ProductsResponse fromList(@NonNull ArrayList<Object> list) {
      ProductsResponse pigeonResult = new ProductsResponse();
      Object code = list.get(0);
      pigeonResult.setCode((code == null) ? null : ((code instanceof Integer) ? (Integer) code : (Long) code));
      Object errorMessage = list.get(1);
      pigeonResult.setErrorMessage((String) errorMessage);
      Object errorDescription = list.get(2);
      pigeonResult.setErrorDescription((String) errorDescription);
      Object traceId = list.get(3);
      pigeonResult.setTraceId((String) traceId);
      Object products = list.get(4);
      pigeonResult.setProducts((List<Product>) products);
      Object errors = list.get(5);
      pigeonResult.setErrors((List<DigitalShopGeneralError>) errors);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Purchase {
    private @Nullable String purchaseId;

    public @Nullable String getPurchaseId() {
      return purchaseId;
    }

    public void setPurchaseId(@Nullable String setterArg) {
      this.purchaseId = setterArg;
    }

    private @Nullable String productId;

    public @Nullable String getProductId() {
      return productId;
    }

    public void setProductId(@Nullable String setterArg) {
      this.productId = setterArg;
    }

    private @Nullable String description;

    public @Nullable String getDescription() {
      return description;
    }

    public void setDescription(@Nullable String setterArg) {
      this.description = setterArg;
    }

    private @Nullable String language;

    public @Nullable String getLanguage() {
      return language;
    }

    public void setLanguage(@Nullable String setterArg) {
      this.language = setterArg;
    }

    private @Nullable String purchaseTime;

    public @Nullable String getPurchaseTime() {
      return purchaseTime;
    }

    public void setPurchaseTime(@Nullable String setterArg) {
      this.purchaseTime = setterArg;
    }

    private @Nullable String orderId;

    public @Nullable String getOrderId() {
      return orderId;
    }

    public void setOrderId(@Nullable String setterArg) {
      this.orderId = setterArg;
    }

    private @Nullable String amountLabel;

    public @Nullable String getAmountLabel() {
      return amountLabel;
    }

    public void setAmountLabel(@Nullable String setterArg) {
      this.amountLabel = setterArg;
    }

    private @Nullable Long amount;

    public @Nullable Long getAmount() {
      return amount;
    }

    public void setAmount(@Nullable Long setterArg) {
      this.amount = setterArg;
    }

    private @Nullable String currency;

    public @Nullable String getCurrency() {
      return currency;
    }

    public void setCurrency(@Nullable String setterArg) {
      this.currency = setterArg;
    }

    private @Nullable Long quantity;

    public @Nullable Long getQuantity() {
      return quantity;
    }

    public void setQuantity(@Nullable Long setterArg) {
      this.quantity = setterArg;
    }

    private @Nullable String purchaseState;

    public @Nullable String getPurchaseState() {
      return purchaseState;
    }

    public void setPurchaseState(@Nullable String setterArg) {
      this.purchaseState = setterArg;
    }

    private @Nullable String developerPayload;

    public @Nullable String getDeveloperPayload() {
      return developerPayload;
    }

    public void setDeveloperPayload(@Nullable String setterArg) {
      this.developerPayload = setterArg;
    }

    private @Nullable String invoiceId;

    public @Nullable String getInvoiceId() {
      return invoiceId;
    }

    public void setInvoiceId(@Nullable String setterArg) {
      this.invoiceId = setterArg;
    }

    private @Nullable String subscriptionToken;

    public @Nullable String getSubscriptionToken() {
      return subscriptionToken;
    }

    public void setSubscriptionToken(@Nullable String setterArg) {
      this.subscriptionToken = setterArg;
    }

    public static final class Builder {

      private @Nullable String purchaseId;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchaseId(@Nullable String setterArg) {
        this.purchaseId = setterArg;
        return this;
      }

      private @Nullable String productId;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductId(@Nullable String setterArg) {
        this.productId = setterArg;
        return this;
      }

      private @Nullable String description;

      @CanIgnoreReturnValue
      public @NonNull Builder setDescription(@Nullable String setterArg) {
        this.description = setterArg;
        return this;
      }

      private @Nullable String language;

      @CanIgnoreReturnValue
      public @NonNull Builder setLanguage(@Nullable String setterArg) {
        this.language = setterArg;
        return this;
      }

      private @Nullable String purchaseTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchaseTime(@Nullable String setterArg) {
        this.purchaseTime = setterArg;
        return this;
      }

      private @Nullable String orderId;

      @CanIgnoreReturnValue
      public @NonNull Builder setOrderId(@Nullable String setterArg) {
        this.orderId = setterArg;
        return this;
      }

      private @Nullable String amountLabel;

      @CanIgnoreReturnValue
      public @NonNull Builder setAmountLabel(@Nullable String setterArg) {
        this.amountLabel = setterArg;
        return this;
      }

      private @Nullable Long amount;

      @CanIgnoreReturnValue
      public @NonNull Builder setAmount(@Nullable Long setterArg) {
        this.amount = setterArg;
        return this;
      }

      private @Nullable String currency;

      @CanIgnoreReturnValue
      public @NonNull Builder setCurrency(@Nullable String setterArg) {
        this.currency = setterArg;
        return this;
      }

      private @Nullable Long quantity;

      @CanIgnoreReturnValue
      public @NonNull Builder setQuantity(@Nullable Long setterArg) {
        this.quantity = setterArg;
        return this;
      }

      private @Nullable String purchaseState;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchaseState(@Nullable String setterArg) {
        this.purchaseState = setterArg;
        return this;
      }

      private @Nullable String developerPayload;

      @CanIgnoreReturnValue
      public @NonNull Builder setDeveloperPayload(@Nullable String setterArg) {
        this.developerPayload = setterArg;
        return this;
      }

      private @Nullable String invoiceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvoiceId(@Nullable String setterArg) {
        this.invoiceId = setterArg;
        return this;
      }

      private @Nullable String subscriptionToken;

      @CanIgnoreReturnValue
      public @NonNull Builder setSubscriptionToken(@Nullable String setterArg) {
        this.subscriptionToken = setterArg;
        return this;
      }

      public @NonNull Purchase build() {
        Purchase pigeonReturn = new Purchase();
        pigeonReturn.setPurchaseId(purchaseId);
        pigeonReturn.setProductId(productId);
        pigeonReturn.setDescription(description);
        pigeonReturn.setLanguage(language);
        pigeonReturn.setPurchaseTime(purchaseTime);
        pigeonReturn.setOrderId(orderId);
        pigeonReturn.setAmountLabel(amountLabel);
        pigeonReturn.setAmount(amount);
        pigeonReturn.setCurrency(currency);
        pigeonReturn.setQuantity(quantity);
        pigeonReturn.setPurchaseState(purchaseState);
        pigeonReturn.setDeveloperPayload(developerPayload);
        pigeonReturn.setInvoiceId(invoiceId);
        pigeonReturn.setSubscriptionToken(subscriptionToken);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(14);
      toListResult.add(purchaseId);
      toListResult.add(productId);
      toListResult.add(description);
      toListResult.add(language);
      toListResult.add(purchaseTime);
      toListResult.add(orderId);
      toListResult.add(amountLabel);
      toListResult.add(amount);
      toListResult.add(currency);
      toListResult.add(quantity);
      toListResult.add(purchaseState);
      toListResult.add(developerPayload);
      toListResult.add(invoiceId);
      toListResult.add(subscriptionToken);
      return toListResult;
    }

    static @NonNull Purchase fromList(@NonNull ArrayList<Object> list) {
      Purchase pigeonResult = new Purchase();
      Object purchaseId = list.get(0);
      pigeonResult.setPurchaseId((String) purchaseId);
      Object productId = list.get(1);
      pigeonResult.setProductId((String) productId);
      Object description = list.get(2);
      pigeonResult.setDescription((String) description);
      Object language = list.get(3);
      pigeonResult.setLanguage((String) language);
      Object purchaseTime = list.get(4);
      pigeonResult.setPurchaseTime((String) purchaseTime);
      Object orderId = list.get(5);
      pigeonResult.setOrderId((String) orderId);
      Object amountLabel = list.get(6);
      pigeonResult.setAmountLabel((String) amountLabel);
      Object amount = list.get(7);
      pigeonResult.setAmount((amount == null) ? null : ((amount instanceof Integer) ? (Integer) amount : (Long) amount));
      Object currency = list.get(8);
      pigeonResult.setCurrency((String) currency);
      Object quantity = list.get(9);
      pigeonResult.setQuantity((quantity == null) ? null : ((quantity instanceof Integer) ? (Integer) quantity : (Long) quantity));
      Object purchaseState = list.get(10);
      pigeonResult.setPurchaseState((String) purchaseState);
      Object developerPayload = list.get(11);
      pigeonResult.setDeveloperPayload((String) developerPayload);
      Object invoiceId = list.get(12);
      pigeonResult.setInvoiceId((String) invoiceId);
      Object subscriptionToken = list.get(13);
      pigeonResult.setSubscriptionToken((String) subscriptionToken);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class PurchasesResponse {
    private @NonNull Long code;

    public @NonNull Long getCode() {
      return code;
    }

    public void setCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"code\" is null.");
      }
      this.code = setterArg;
    }

    private @Nullable String errorMessage;

    public @Nullable String getErrorMessage() {
      return errorMessage;
    }

    public void setErrorMessage(@Nullable String setterArg) {
      this.errorMessage = setterArg;
    }

    private @Nullable String errorDescription;

    public @Nullable String getErrorDescription() {
      return errorDescription;
    }

    public void setErrorDescription(@Nullable String setterArg) {
      this.errorDescription = setterArg;
    }

    private @Nullable String traceId;

    public @Nullable String getTraceId() {
      return traceId;
    }

    public void setTraceId(@Nullable String setterArg) {
      this.traceId = setterArg;
    }

    private @NonNull List<Purchase> purchases;

    public @NonNull List<Purchase> getPurchases() {
      return purchases;
    }

    public void setPurchases(@NonNull List<Purchase> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"purchases\" is null.");
      }
      this.purchases = setterArg;
    }

    private @NonNull List<DigitalShopGeneralError> errors;

    public @NonNull List<DigitalShopGeneralError> getErrors() {
      return errors;
    }

    public void setErrors(@NonNull List<DigitalShopGeneralError> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"errors\" is null.");
      }
      this.errors = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PurchasesResponse() {}

    public static final class Builder {

      private @Nullable Long code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@NonNull Long setterArg) {
        this.code = setterArg;
        return this;
      }

      private @Nullable String errorMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorMessage(@Nullable String setterArg) {
        this.errorMessage = setterArg;
        return this;
      }

      private @Nullable String errorDescription;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorDescription(@Nullable String setterArg) {
        this.errorDescription = setterArg;
        return this;
      }

      private @Nullable String traceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setTraceId(@Nullable String setterArg) {
        this.traceId = setterArg;
        return this;
      }

      private @Nullable List<Purchase> purchases;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchases(@NonNull List<Purchase> setterArg) {
        this.purchases = setterArg;
        return this;
      }

      private @Nullable List<DigitalShopGeneralError> errors;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrors(@NonNull List<DigitalShopGeneralError> setterArg) {
        this.errors = setterArg;
        return this;
      }

      public @NonNull PurchasesResponse build() {
        PurchasesResponse pigeonReturn = new PurchasesResponse();
        pigeonReturn.setCode(code);
        pigeonReturn.setErrorMessage(errorMessage);
        pigeonReturn.setErrorDescription(errorDescription);
        pigeonReturn.setTraceId(traceId);
        pigeonReturn.setPurchases(purchases);
        pigeonReturn.setErrors(errors);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add(code);
      toListResult.add(errorMessage);
      toListResult.add(errorDescription);
      toListResult.add(traceId);
      toListResult.add(purchases);
      toListResult.add(errors);
      return toListResult;
    }

    static @NonNull PurchasesResponse fromList(@NonNull ArrayList<Object> list) {
      PurchasesResponse pigeonResult = new PurchasesResponse();
      Object code = list.get(0);
      pigeonResult.setCode((code == null) ? null : ((code instanceof Integer) ? (Integer) code : (Long) code));
      Object errorMessage = list.get(1);
      pigeonResult.setErrorMessage((String) errorMessage);
      Object errorDescription = list.get(2);
      pigeonResult.setErrorDescription((String) errorDescription);
      Object traceId = list.get(3);
      pigeonResult.setTraceId((String) traceId);
      Object purchases = list.get(4);
      pigeonResult.setPurchases((List<Purchase>) purchases);
      Object errors = list.get(5);
      pigeonResult.setErrors((List<DigitalShopGeneralError>) errors);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ConfirmPurchaseResponse {
    private @NonNull Boolean success;

    public @NonNull Boolean getSuccess() {
      return success;
    }

    public void setSuccess(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"success\" is null.");
      }
      this.success = setterArg;
    }

    private @Nullable String errorMessage;

    public @Nullable String getErrorMessage() {
      return errorMessage;
    }

    public void setErrorMessage(@Nullable String setterArg) {
      this.errorMessage = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ConfirmPurchaseResponse() {}

    public static final class Builder {

      private @Nullable Boolean success;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccess(@NonNull Boolean setterArg) {
        this.success = setterArg;
        return this;
      }

      private @Nullable String errorMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorMessage(@Nullable String setterArg) {
        this.errorMessage = setterArg;
        return this;
      }

      public @NonNull ConfirmPurchaseResponse build() {
        ConfirmPurchaseResponse pigeonReturn = new ConfirmPurchaseResponse();
        pigeonReturn.setSuccess(success);
        pigeonReturn.setErrorMessage(errorMessage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(success);
      toListResult.add(errorMessage);
      return toListResult;
    }

    static @NonNull ConfirmPurchaseResponse fromList(@NonNull ArrayList<Object> list) {
      ConfirmPurchaseResponse pigeonResult = new ConfirmPurchaseResponse();
      Object success = list.get(0);
      pigeonResult.setSuccess((Boolean) success);
      Object errorMessage = list.get(1);
      pigeonResult.setErrorMessage((String) errorMessage);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class PaymentResult {
    private @Nullable SuccessInvoice successInvoice;

    public @Nullable SuccessInvoice getSuccessInvoice() {
      return successInvoice;
    }

    public void setSuccessInvoice(@Nullable SuccessInvoice setterArg) {
      this.successInvoice = setterArg;
    }

    private @Nullable InvalidInvoice invalidInvoice;

    public @Nullable InvalidInvoice getInvalidInvoice() {
      return invalidInvoice;
    }

    public void setInvalidInvoice(@Nullable InvalidInvoice setterArg) {
      this.invalidInvoice = setterArg;
    }

    private @Nullable SuccessPurchase successPurchase;

    public @Nullable SuccessPurchase getSuccessPurchase() {
      return successPurchase;
    }

    public void setSuccessPurchase(@Nullable SuccessPurchase setterArg) {
      this.successPurchase = setterArg;
    }

    private @Nullable InvalidPurchase invalidPurchase;

    public @Nullable InvalidPurchase getInvalidPurchase() {
      return invalidPurchase;
    }

    public void setInvalidPurchase(@Nullable InvalidPurchase setterArg) {
      this.invalidPurchase = setterArg;
    }

    public static final class Builder {

      private @Nullable SuccessInvoice successInvoice;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccessInvoice(@Nullable SuccessInvoice setterArg) {
        this.successInvoice = setterArg;
        return this;
      }

      private @Nullable InvalidInvoice invalidInvoice;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvalidInvoice(@Nullable InvalidInvoice setterArg) {
        this.invalidInvoice = setterArg;
        return this;
      }

      private @Nullable SuccessPurchase successPurchase;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccessPurchase(@Nullable SuccessPurchase setterArg) {
        this.successPurchase = setterArg;
        return this;
      }

      private @Nullable InvalidPurchase invalidPurchase;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvalidPurchase(@Nullable InvalidPurchase setterArg) {
        this.invalidPurchase = setterArg;
        return this;
      }

      public @NonNull PaymentResult build() {
        PaymentResult pigeonReturn = new PaymentResult();
        pigeonReturn.setSuccessInvoice(successInvoice);
        pigeonReturn.setInvalidInvoice(invalidInvoice);
        pigeonReturn.setSuccessPurchase(successPurchase);
        pigeonReturn.setInvalidPurchase(invalidPurchase);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(4);
      toListResult.add((successInvoice == null) ? null : successInvoice.toList());
      toListResult.add((invalidInvoice == null) ? null : invalidInvoice.toList());
      toListResult.add((successPurchase == null) ? null : successPurchase.toList());
      toListResult.add((invalidPurchase == null) ? null : invalidPurchase.toList());
      return toListResult;
    }

    static @NonNull PaymentResult fromList(@NonNull ArrayList<Object> list) {
      PaymentResult pigeonResult = new PaymentResult();
      Object successInvoice = list.get(0);
      pigeonResult.setSuccessInvoice((successInvoice == null) ? null : SuccessInvoice.fromList((ArrayList<Object>) successInvoice));
      Object invalidInvoice = list.get(1);
      pigeonResult.setInvalidInvoice((invalidInvoice == null) ? null : InvalidInvoice.fromList((ArrayList<Object>) invalidInvoice));
      Object successPurchase = list.get(2);
      pigeonResult.setSuccessPurchase((successPurchase == null) ? null : SuccessPurchase.fromList((ArrayList<Object>) successPurchase));
      Object invalidPurchase = list.get(3);
      pigeonResult.setInvalidPurchase((invalidPurchase == null) ? null : InvalidPurchase.fromList((ArrayList<Object>) invalidPurchase));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SuccessInvoice {
    private @NonNull String invoiceId;

    public @NonNull String getInvoiceId() {
      return invoiceId;
    }

    public void setInvoiceId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"invoiceId\" is null.");
      }
      this.invoiceId = setterArg;
    }

    private @NonNull String finishCode;

    public @NonNull String getFinishCode() {
      return finishCode;
    }

    public void setFinishCode(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"finishCode\" is null.");
      }
      this.finishCode = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SuccessInvoice() {}

    public static final class Builder {

      private @Nullable String invoiceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvoiceId(@NonNull String setterArg) {
        this.invoiceId = setterArg;
        return this;
      }

      private @Nullable String finishCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setFinishCode(@NonNull String setterArg) {
        this.finishCode = setterArg;
        return this;
      }

      public @NonNull SuccessInvoice build() {
        SuccessInvoice pigeonReturn = new SuccessInvoice();
        pigeonReturn.setInvoiceId(invoiceId);
        pigeonReturn.setFinishCode(finishCode);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(invoiceId);
      toListResult.add(finishCode);
      return toListResult;
    }

    static @NonNull SuccessInvoice fromList(@NonNull ArrayList<Object> list) {
      SuccessInvoice pigeonResult = new SuccessInvoice();
      Object invoiceId = list.get(0);
      pigeonResult.setInvoiceId((String) invoiceId);
      Object finishCode = list.get(1);
      pigeonResult.setFinishCode((String) finishCode);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class InvalidInvoice {
    private @Nullable String invoiceId;

    public @Nullable String getInvoiceId() {
      return invoiceId;
    }

    public void setInvoiceId(@Nullable String setterArg) {
      this.invoiceId = setterArg;
    }

    public static final class Builder {

      private @Nullable String invoiceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvoiceId(@Nullable String setterArg) {
        this.invoiceId = setterArg;
        return this;
      }

      public @NonNull InvalidInvoice build() {
        InvalidInvoice pigeonReturn = new InvalidInvoice();
        pigeonReturn.setInvoiceId(invoiceId);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(invoiceId);
      return toListResult;
    }

    static @NonNull InvalidInvoice fromList(@NonNull ArrayList<Object> list) {
      InvalidInvoice pigeonResult = new InvalidInvoice();
      Object invoiceId = list.get(0);
      pigeonResult.setInvoiceId((String) invoiceId);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SuccessPurchase {
    private @Nullable String finishCode;

    public @Nullable String getFinishCode() {
      return finishCode;
    }

    public void setFinishCode(@Nullable String setterArg) {
      this.finishCode = setterArg;
    }

    private @Nullable String orderId;

    public @Nullable String getOrderId() {
      return orderId;
    }

    public void setOrderId(@Nullable String setterArg) {
      this.orderId = setterArg;
    }

    private @NonNull String purchaseId;

    public @NonNull String getPurchaseId() {
      return purchaseId;
    }

    public void setPurchaseId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"purchaseId\" is null.");
      }
      this.purchaseId = setterArg;
    }

    private @NonNull String productId;

    public @NonNull String getProductId() {
      return productId;
    }

    public void setProductId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"productId\" is null.");
      }
      this.productId = setterArg;
    }

    private @Nullable String invoiceId;

    public @Nullable String getInvoiceId() {
      return invoiceId;
    }

    public void setInvoiceId(@Nullable String setterArg) {
      this.invoiceId = setterArg;
    }

    private @Nullable String subscriptionToken;

    public @Nullable String getSubscriptionToken() {
      return subscriptionToken;
    }

    public void setSubscriptionToken(@Nullable String setterArg) {
      this.subscriptionToken = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SuccessPurchase() {}

    public static final class Builder {

      private @Nullable String finishCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setFinishCode(@Nullable String setterArg) {
        this.finishCode = setterArg;
        return this;
      }

      private @Nullable String orderId;

      @CanIgnoreReturnValue
      public @NonNull Builder setOrderId(@Nullable String setterArg) {
        this.orderId = setterArg;
        return this;
      }

      private @Nullable String purchaseId;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchaseId(@NonNull String setterArg) {
        this.purchaseId = setterArg;
        return this;
      }

      private @Nullable String productId;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductId(@NonNull String setterArg) {
        this.productId = setterArg;
        return this;
      }

      private @Nullable String invoiceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvoiceId(@Nullable String setterArg) {
        this.invoiceId = setterArg;
        return this;
      }

      private @Nullable String subscriptionToken;

      @CanIgnoreReturnValue
      public @NonNull Builder setSubscriptionToken(@Nullable String setterArg) {
        this.subscriptionToken = setterArg;
        return this;
      }

      public @NonNull SuccessPurchase build() {
        SuccessPurchase pigeonReturn = new SuccessPurchase();
        pigeonReturn.setFinishCode(finishCode);
        pigeonReturn.setOrderId(orderId);
        pigeonReturn.setPurchaseId(purchaseId);
        pigeonReturn.setProductId(productId);
        pigeonReturn.setInvoiceId(invoiceId);
        pigeonReturn.setSubscriptionToken(subscriptionToken);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add(finishCode);
      toListResult.add(orderId);
      toListResult.add(purchaseId);
      toListResult.add(productId);
      toListResult.add(invoiceId);
      toListResult.add(subscriptionToken);
      return toListResult;
    }

    static @NonNull SuccessPurchase fromList(@NonNull ArrayList<Object> list) {
      SuccessPurchase pigeonResult = new SuccessPurchase();
      Object finishCode = list.get(0);
      pigeonResult.setFinishCode((String) finishCode);
      Object orderId = list.get(1);
      pigeonResult.setOrderId((String) orderId);
      Object purchaseId = list.get(2);
      pigeonResult.setPurchaseId((String) purchaseId);
      Object productId = list.get(3);
      pigeonResult.setProductId((String) productId);
      Object invoiceId = list.get(4);
      pigeonResult.setInvoiceId((String) invoiceId);
      Object subscriptionToken = list.get(5);
      pigeonResult.setSubscriptionToken((String) subscriptionToken);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class InvalidPurchase {
    private @Nullable String purchaseId;

    public @Nullable String getPurchaseId() {
      return purchaseId;
    }

    public void setPurchaseId(@Nullable String setterArg) {
      this.purchaseId = setterArg;
    }

    private @Nullable String invoiceId;

    public @Nullable String getInvoiceId() {
      return invoiceId;
    }

    public void setInvoiceId(@Nullable String setterArg) {
      this.invoiceId = setterArg;
    }

    private @Nullable String orderId;

    public @Nullable String getOrderId() {
      return orderId;
    }

    public void setOrderId(@Nullable String setterArg) {
      this.orderId = setterArg;
    }

    private @Nullable Long quantity;

    public @Nullable Long getQuantity() {
      return quantity;
    }

    public void setQuantity(@Nullable Long setterArg) {
      this.quantity = setterArg;
    }

    private @Nullable String productId;

    public @Nullable String getProductId() {
      return productId;
    }

    public void setProductId(@Nullable String setterArg) {
      this.productId = setterArg;
    }

    private @Nullable Long errorCode;

    public @Nullable Long getErrorCode() {
      return errorCode;
    }

    public void setErrorCode(@Nullable Long setterArg) {
      this.errorCode = setterArg;
    }

    public static final class Builder {

      private @Nullable String purchaseId;

      @CanIgnoreReturnValue
      public @NonNull Builder setPurchaseId(@Nullable String setterArg) {
        this.purchaseId = setterArg;
        return this;
      }

      private @Nullable String invoiceId;

      @CanIgnoreReturnValue
      public @NonNull Builder setInvoiceId(@Nullable String setterArg) {
        this.invoiceId = setterArg;
        return this;
      }

      private @Nullable String orderId;

      @CanIgnoreReturnValue
      public @NonNull Builder setOrderId(@Nullable String setterArg) {
        this.orderId = setterArg;
        return this;
      }

      private @Nullable Long quantity;

      @CanIgnoreReturnValue
      public @NonNull Builder setQuantity(@Nullable Long setterArg) {
        this.quantity = setterArg;
        return this;
      }

      private @Nullable String productId;

      @CanIgnoreReturnValue
      public @NonNull Builder setProductId(@Nullable String setterArg) {
        this.productId = setterArg;
        return this;
      }

      private @Nullable Long errorCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorCode(@Nullable Long setterArg) {
        this.errorCode = setterArg;
        return this;
      }

      public @NonNull InvalidPurchase build() {
        InvalidPurchase pigeonReturn = new InvalidPurchase();
        pigeonReturn.setPurchaseId(purchaseId);
        pigeonReturn.setInvoiceId(invoiceId);
        pigeonReturn.setOrderId(orderId);
        pigeonReturn.setQuantity(quantity);
        pigeonReturn.setProductId(productId);
        pigeonReturn.setErrorCode(errorCode);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add(purchaseId);
      toListResult.add(invoiceId);
      toListResult.add(orderId);
      toListResult.add(quantity);
      toListResult.add(productId);
      toListResult.add(errorCode);
      return toListResult;
    }

    static @NonNull InvalidPurchase fromList(@NonNull ArrayList<Object> list) {
      InvalidPurchase pigeonResult = new InvalidPurchase();
      Object purchaseId = list.get(0);
      pigeonResult.setPurchaseId((String) purchaseId);
      Object invoiceId = list.get(1);
      pigeonResult.setInvoiceId((String) invoiceId);
      Object orderId = list.get(2);
      pigeonResult.setOrderId((String) orderId);
      Object quantity = list.get(3);
      pigeonResult.setQuantity((quantity == null) ? null : ((quantity instanceof Integer) ? (Integer) quantity : (Long) quantity));
      Object productId = list.get(4);
      pigeonResult.setProductId((String) productId);
      Object errorCode = list.get(5);
      pigeonResult.setErrorCode((errorCode == null) ? null : ((errorCode instanceof Integer) ? (Integer) errorCode : (Long) errorCode));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DigitalShopGeneralError {
    private @Nullable String name;

    public @Nullable String getName() {
      return name;
    }

    public void setName(@Nullable String setterArg) {
      this.name = setterArg;
    }

    private @Nullable Long code;

    public @Nullable Long getCode() {
      return code;
    }

    public void setCode(@Nullable Long setterArg) {
      this.code = setterArg;
    }

    private @Nullable String description;

    public @Nullable String getDescription() {
      return description;
    }

    public void setDescription(@Nullable String setterArg) {
      this.description = setterArg;
    }

    public static final class Builder {

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@Nullable String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable Long code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@Nullable Long setterArg) {
        this.code = setterArg;
        return this;
      }

      private @Nullable String description;

      @CanIgnoreReturnValue
      public @NonNull Builder setDescription(@Nullable String setterArg) {
        this.description = setterArg;
        return this;
      }

      public @NonNull DigitalShopGeneralError build() {
        DigitalShopGeneralError pigeonReturn = new DigitalShopGeneralError();
        pigeonReturn.setName(name);
        pigeonReturn.setCode(code);
        pigeonReturn.setDescription(description);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(name);
      toListResult.add(code);
      toListResult.add(description);
      return toListResult;
    }

    static @NonNull DigitalShopGeneralError fromList(@NonNull ArrayList<Object> list) {
      DigitalShopGeneralError pigeonResult = new DigitalShopGeneralError();
      Object name = list.get(0);
      pigeonResult.setName((String) name);
      Object code = list.get(1);
      pigeonResult.setCode((code == null) ? null : ((code instanceof Integer) ? (Integer) code : (Long) code));
      Object description = list.get(2);
      pigeonResult.setDescription((String) description);
      return pigeonResult;
    }
  }

  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }

  private static class RustoreBillingCodec extends StandardMessageCodec {
    public static final RustoreBillingCodec INSTANCE = new RustoreBillingCodec();

    private RustoreBillingCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return ConfirmPurchaseResponse.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 129:
          return DigitalShopGeneralError.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return InvalidInvoice.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return InvalidPurchase.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return PaymentResult.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return Product.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return ProductsResponse.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return Purchase.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return PurchasesResponse.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 137:
          return Subscription.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 138:
          return SubscriptionPeriod.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 139:
          return SuccessInvoice.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 140:
          return SuccessPurchase.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof ConfirmPurchaseResponse) {
        stream.write(128);
        writeValue(stream, ((ConfirmPurchaseResponse) value).toList());
      } else if (value instanceof DigitalShopGeneralError) {
        stream.write(129);
        writeValue(stream, ((DigitalShopGeneralError) value).toList());
      } else if (value instanceof InvalidInvoice) {
        stream.write(130);
        writeValue(stream, ((InvalidInvoice) value).toList());
      } else if (value instanceof InvalidPurchase) {
        stream.write(131);
        writeValue(stream, ((InvalidPurchase) value).toList());
      } else if (value instanceof PaymentResult) {
        stream.write(132);
        writeValue(stream, ((PaymentResult) value).toList());
      } else if (value instanceof Product) {
        stream.write(133);
        writeValue(stream, ((Product) value).toList());
      } else if (value instanceof ProductsResponse) {
        stream.write(134);
        writeValue(stream, ((ProductsResponse) value).toList());
      } else if (value instanceof Purchase) {
        stream.write(135);
        writeValue(stream, ((Purchase) value).toList());
      } else if (value instanceof PurchasesResponse) {
        stream.write(136);
        writeValue(stream, ((PurchasesResponse) value).toList());
      } else if (value instanceof Subscription) {
        stream.write(137);
        writeValue(stream, ((Subscription) value).toList());
      } else if (value instanceof SubscriptionPeriod) {
        stream.write(138);
        writeValue(stream, ((SubscriptionPeriod) value).toList());
      } else if (value instanceof SuccessInvoice) {
        stream.write(139);
        writeValue(stream, ((SuccessInvoice) value).toList());
      } else if (value instanceof SuccessPurchase) {
        stream.write(140);
        writeValue(stream, ((SuccessPurchase) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface RustoreBilling {

    void initialize(@NonNull String id, @NonNull String prefix, @NonNull Boolean debugLogs, @Nullable Boolean allowNativeErrorHadling, @NonNull Result<String> result);

    void available(@NonNull Result<Boolean> result);

    void products(@NonNull List<String> ids, @NonNull Result<ProductsResponse> result);

    void purchases(@NonNull Result<PurchasesResponse> result);

    void purchase(@NonNull String id, @Nullable String developerPayload, @NonNull Result<PaymentResult> result);

    void purchaseInfo(@NonNull String id, @NonNull Result<Purchase> result);

    void confirm(@NonNull String id, @NonNull Result<ConfirmPurchaseResponse> result);

    /** The codec used by RustoreBilling. */
    static @NonNull MessageCodec<Object> getCodec() {
      return RustoreBillingCodec.INSTANCE;
    }
    /**Sets up an instance of `RustoreBilling` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable RustoreBilling api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.initialize", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String idArg = (String) args.get(0);
                String prefixArg = (String) args.get(1);
                Boolean debugLogsArg = (Boolean) args.get(2);
                Boolean allowNativeErrorHadlingArg = (Boolean) args.get(3);
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.initialize(idArg, prefixArg, debugLogsArg, allowNativeErrorHadlingArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.available", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.available(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.products", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                List<String> idsArg = (List<String>) args.get(0);
                Result<ProductsResponse> resultCallback =
                    new Result<ProductsResponse>() {
                      public void success(ProductsResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.products(idsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.purchases", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                Result<PurchasesResponse> resultCallback =
                    new Result<PurchasesResponse>() {
                      public void success(PurchasesResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.purchases(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.purchase", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String idArg = (String) args.get(0);
                String developerPayloadArg = (String) args.get(1);
                Result<PaymentResult> resultCallback =
                    new Result<PaymentResult>() {
                      public void success(PaymentResult result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.purchase(idArg, developerPayloadArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.purchaseInfo", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String idArg = (String) args.get(0);
                Result<Purchase> resultCallback =
                    new Result<Purchase>() {
                      public void success(Purchase result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.purchaseInfo(idArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_billing.RustoreBilling.confirm", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String idArg = (String) args.get(0);
                Result<ConfirmPurchaseResponse> resultCallback =
                    new Result<ConfirmPurchaseResponse>() {
                      public void success(ConfirmPurchaseResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.confirm(idArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
